# Generated by Django 3.1.7 on 2021-02-27 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='image',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
