# Generated by Django 3.1.7 on 2021-02-28 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz_attempted',
            name='quiz',
        ),
    ]
