# Generated by Django 3.1.7 on 2021-02-27 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210227_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='ans_text',
            field=models.TextField(null=True),
        ),
    ]
